name: ZAProxy scan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: "ZAP Baseline Scan"
        uses: zaproxy/action-baseline@v0.6.1
        with:
        # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'http://testphp.vulnweb.com' 