name: ZAProxy scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.3.0
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://www.admingb.com/'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif