name: ZAProxy scan
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: "ZAP API Scan"
        uses: zaproxy/action-api-scan@v0.1.0
        with:
        # https://github.com/OWASP/OWASP-VWAD/blob/master/src/data/online.json
          target: 'http://testphp.vulnweb.com'   